import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function Home() {

  const [users, setUsers] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const res = await axios.get('/users');
      setUsers(res.data);
    }

    fetchData();

  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </div>
  )
}
